/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.kotlin-application-conventions")
    id("io.freefair.lombok") version "9.2.0"
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))

    // Tests
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.4")


    implementation("dev.langchain4j:langchain4j-open-ai:1.10.0")
    implementation("dev.langchain4j:langchain4j-anthropic:1.10.0")
    implementation(platform("dev.langchain4j:langchain4j-bom:1.10.0"))
    
    // Logging
    implementation("ch.qos.logback:logback-classic:1.5.0")
    implementation("io.github.microutils:kotlin-logging-jvm:3.0.5")
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.AppKt"
}

// Use JUnit Platform for tests
tasks.test {
    useJUnitPlatform()
}
